export const keys = [
    'stick'=
    [
        {
            name:'stick-1001',
            where:'k2-peekhole',
            key:'E6B16405'
        },
        {
            name:'stick-1002',
            where:'k2-wall-big-button',
            key:'FA5CB5F2'
        },
        {
            name:'stick-1003',
            where:'k2-klatrebane',
            key:'6FE718DC'
        },
        {
            name:'stick-1004',
            where:'k2-klatrebane',
            key:'0F9643CE'
        },
        {
            name:'stick-1005',
            where:'k2-klatrebane',
            key:'B771AD71'
        },
        {
            name:'stick-1006',
            where:'k2-tyverialarm',
            key:'F3539DBD'
        },
        {
            name:'stick-1007',
            where:'K2-Poster-Pir',
            key:'43B7D367'
        },
        {
            name:'stick-1008',
            where:'K2-Hue-Footbutton',
            key:'49E57DD8'
        },
        {
            name:'stick-1009',
            where:'K2-Office-Actuator',
            key:'9CBA7418'
        },
        {
            name:'ejdersted-2-lys',
            where:'Ejderstedgade',
            key:'9ED534D7'
        },
        {
            name:'stick-1010',
            where:'K2-Rainbow-Stick',
            key:'C91CC05D'
        },
    ],
    'atom'=
    [
        {
            name:'atom-1001',
            where:'k2-illusion-button',
            key:'DBA46070'
        },
        {
            name:'emmy',
            where:'nora-lys',
            key:'ADC09BFC'
        },
        {
            name:'1',
            where:'k2',
            key:'6EA27505'
        },
        {
            name:'ejderstedgade vitrine',
            where:'ejdersted',
            key:'4E7F1DD6'
        },
        {
            name:'3',
            where:'k2',
            key:'49A3D7C2'
        },
        {
            name:'4 - record buttons',
            where:'k2',
            key:'E36D334E'
        },
        {
            name:'5',
            where:'k2',
            key:'F7976C0E'
        },
        {
            name:'K2-on-air-sign',
            where:'k2',
            key:'45D9F7BB'
        },
        {
            name:'7',
            where:'k2',
            key:'7A697930'
        },
        {
            name:'8',
            where:'k2',
            key:'2BCCE9EB'
        },
        {
            name:'9',
            where:'k2-boards-of-canada',
            key:'53B28FE9'
        },
        {
            name:'10',
            where:'k2',
            key:'F818AC4C'
        },
        {
            name:'11',
            where:'k2',
            key:'609EF6A3'
        },
        {
            name:'12',
            where:'k2',
            key:'B72591E7'
        },
        {
            name:'13',
            where:'k2',
            key:'4DB0FDEC'
        },
        {
            name:'14',
            where:'k2',
            key:'CF9778A3'
        },
        {
            name:'15',
            where:'k2',
            key:'9771DDEB'
        },
        {
            name:'16',
            where:'k2',
            key:'362C35A5'
        },
        {
            name:'17',
            where:'k2',
            key:'1F727AC1'
        },
        {
            name:'18',
            where:'k2',
            key:'5F500E2F'
        },
        {
            name:'19',
            where:'k2',
            key:'95F36A24'
        },
        {
            name:'20',
            where:'k2',
            key:'4E7F1DD6'
        },
         {
            name:'21',
            where:'k2',
            key:'B2A0051E'
        },
         {
            name:'Alborada',
            where:'k2-Basement room',
            key:'0D2BD2C6'
        },
         {
            name:'23',
            where:'k2',
            key:'A1DDE878'
        },
         {
            name:'24',
            where:'k2',
            key:'50C5FE8D'
        },
        {
            name:'25',
            where:'k2',
            key:'B9C26A64'
        },
        {
            name:'26',
            where:'k2',
            key:'E36D334E'
        },
        {
            name:'27',
            where:'k2',
            key:'F36A39C6'
        },
    ],
        'hue-users'= [
            {
                'name':'K2',
                'username': 'kgMgko5iDYljmA3ERym5GDibEkDzQTxutUSDqN36'
            }
        ]
] 
