export const keys = [
    'stick'=
    [
        {
            name:'stick-1001',
            where:'k2-wall-mount',
            key:'E6B16405'
        },
        {
            name:'stick-1002',
            where:'k2-wall-big-button',
            key:'FA5CB5F2'
        },
        {
            name:'stick-1003',
            where:'k2-klatrebane',
            key:'6FE718DC'
        },
        {
            name:'stick-1004',
            where:'k2-klatrebane',
            key:'0F9643CE'
        },
        {
            name:'stick-1005',
            where:'k2-klatrebane',
            key:'B771AD71'
        },
        {
            name:'stick-1006',
            where:'k2-tyverialarm',
            key:'F3539DBD'
        }
    ],
    'atom'=
    [
        {
            name:'atom-1001',
            where:'k2',
            key:'DBA46070'
        }
    ]
] 