export const keys = [
    'stick'=
    [
        {
            name:'stick-1001',
            where:'k2-peekhole',
            key:'E6B16405'
        },
        {
            name:'stick-1002',
            where:'k2-wall-big-button',
            key:'FA5CB5F2'
        },
        {
            name:'stick-1003',
            where:'k2-klatrebane',
            key:'6FE718DC'
        },
        {
            name:'stick-1004',
            where:'k2-klatrebane',
            key:'0F9643CE'
        },
        {
            name:'stick-1005',
            where:'k2-klatrebane',
            key:'B771AD71'
        },
        {
            name:'stick-1006',
            where:'k2-tyverialarm',
            key:'F3539DBD'
        }
    ],
    'atom'=
    [
        {
            name:'atom-1001',
            where:'k2-illusion-button',
            key:'DBA46070'
        },
        {
            name:'1',
            where:'k2',
            key:'6EA27505'
        },
        {
            name:'2',
            where:'k2',
            key:'7DD009A3'
        },
        {
            name:'3',
            where:'k2',
            key:'49A3D7C2'
        },
        {
            name:'4',
            where:'k2',
            key:'E36D334E'
        },
        {
            name:'5',
            where:'k2',
            key:'F7976C0E'
        },
        {
            name:'6',
            where:'k2',
            key:'45D9F7BB'
        },
        {
            name:'7',
            where:'k2',
            key:'7A697930'
        },
        {
            name:'8',
            where:'k2',
            key:'2BCCE9EB'
        },
    ],
        'hue-users'= [
            {
                'name':'K2',
                'username': 'kgMgko5iDYljmA3ERym5GDibEkDzQTxutUSDqN36'
            }
        ]
] 
